### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This brings CI to this repository.

@epage Hi! We talked about this in the CLI-WG meetup yesterday and I now had a quick look at this - and I like what this crate does.

So if you want, please give me maintainers access! I want to add CI and implement a [bors](https://bors.tech) based workflow and then bring this crate back into shape!

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
This PR is of course not ready yet :laughing:

**Comment by matthiasbeyer** [comment]
bors ping

**Comment by matthiasbeyer** [comment]
@epage can you see why actions is not triggered? I fail to see it right now...

**Comment by epage** [comment]
Nothing stands out to me.  All I can think of is to pair it down to root cause which part github doesn't like

**Comment by matthiasbeyer** [comment]
Also githubstatus.com does not report anything right now. Strange.

**Comment by matthiasbeyer** [comment]
I am gonna re-create this PR and we will see whether actions will run then...

**Pull request closed without merging**
